#[derive(Debug, Clone)]
pub struct OPCODE {
    pub opcode: u8,
    pub name: String,
    pub gas: u16,
    pub oprand_bytes: u8,
    pub stack_reads: u8,
    pub stack_writes: u8,
}

impl TryFrom<u8> for OPCODE {
    type Error = &'static str;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x00 => Ok(OPCODE {
                opcode: 0x00,
                name: "STOP".to_string(),
                gas: 0,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 0,
            }),
            0x01 => Ok(OPCODE {
                opcode: 0x01,
                name: "ADD".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x02 => Ok(OPCODE {
                opcode: 0x02,
                name: "MUL".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x03 => Ok(OPCODE {
                opcode: 0x03,
                name: "SUB".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x04 => Ok(OPCODE {
                opcode: 0x04,
                name: "DIV".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x05 => Ok(OPCODE {
                opcode: 0x05,
                name: "SDIV".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x06 => Ok(OPCODE {
                opcode: 0x06,
                name: "MOD".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x07 => Ok(OPCODE {
                opcode: 0x07,
                name: "SMOD".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x08 => Ok(OPCODE {
                opcode: 0x08,
                name: "ADDMOD".to_string(),
                gas: 8,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 1,
            }),
            0x09 => Ok(OPCODE {
                opcode: 0x09,
                name: "MULMOD".to_string(),
                gas: 8,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 1,
            }),
            0x0a => Ok(OPCODE {
                opcode: 0x0a,
                name: "EXP".to_string(),
                gas: 10,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x0b => Ok(OPCODE {
                opcode: 0x0b,
                name: "SIGNEXTEND".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),

            0x10 => Ok(OPCODE {
                opcode: 0x10,
                name: "LT".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x11 => Ok(OPCODE {
                opcode: 0x11,
                name: "GT".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x12 => Ok(OPCODE {
                opcode: 0x12,
                name: "SLT".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x13 => Ok(OPCODE {
                opcode: 0x13,
                name: "SGT".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x14 => Ok(OPCODE {
                opcode: 0x14,
                name: "EQ".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x15 => Ok(OPCODE {
                opcode: 0x15,
                name: "ISZERO".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x16 => Ok(OPCODE {
                opcode: 0x16,
                name: "AND".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x17 => Ok(OPCODE {
                opcode: 0x17,
                name: "OR".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x18 => Ok(OPCODE {
                opcode: 0x18,
                name: "XOR".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x19 => Ok(OPCODE {
                opcode: 0x19,
                name: "NOT".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x1a => Ok(OPCODE {
                opcode: 0x1a,
                name: "BYTE".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x1b => Ok(OPCODE {
                opcode: 0x1b,
                name: "SHL".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x1c => Ok(OPCODE {
                opcode: 0x1c,
                name: "SHR".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),
            0x1d => Ok(OPCODE {
                opcode: 0x1d,
                name: "SAR".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),

            0x20 => Ok(OPCODE {
                opcode: 0x20,
                name: "SHA3".to_string(),
                gas: 30,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 1,
            }),

            0x30 => Ok(OPCODE {
                opcode: 0x30,
                name: "ADDRESS".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x31 => Ok(OPCODE {
                opcode: 0x31,
                name: "BALANCE".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x32 => Ok(OPCODE {
                opcode: 0x32,
                name: "ORIGIN".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x33 => Ok(OPCODE {
                opcode: 0x33,
                name: "CALLER".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x34 => Ok(OPCODE {
                opcode: 0x34,
                name: "CALLVALUE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x35 => Ok(OPCODE {
                opcode: 0x35,
                name: "CALLDATALOAD".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x36 => Ok(OPCODE {
                opcode: 0x36,
                name: "CALLDATASIZE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x37 => Ok(OPCODE {
                opcode: 0x37,
                name: "CALLDATACOPY".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 0,
            }),
            0x38 => Ok(OPCODE {
                opcode: 0x38,
                name: "CODESIZE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x39 => Ok(OPCODE {
                opcode: 0x39,
                name: "CODECOPY".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 0,
            }),
            0x3a => Ok(OPCODE {
                opcode: 0x3a,
                name: "GASPRICE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x3b => Ok(OPCODE {
                opcode: 0x3b,
                name: "EXTCODESIZE".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x3c => Ok(OPCODE {
                opcode: 0x3c,
                name: "EXTCODECOPY".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 4,
                stack_writes: 0,
            }),
            0x3d => Ok(OPCODE {
                opcode: 0x3d,
                name: "RETURNDATASIZE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x3e => Ok(OPCODE {
                opcode: 0x3e,
                name: "RETURNDATACOPY".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 0,
            }),
            0x3f => Ok(OPCODE {
                opcode: 0x3f,
                name: "EXTCODEHASH".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x40 => Ok(OPCODE {
                opcode: 0x40,
                name: "BLOCKHASH".to_string(),
                gas: 20,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x41 => Ok(OPCODE {
                opcode: 0x41,
                name: "COINBASE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x42 => Ok(OPCODE {
                opcode: 0x42,
                name: "TIMESTAMP".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x43 => Ok(OPCODE {
                opcode: 0x43,
                name: "NUMBER".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x44 => Ok(OPCODE {
                opcode: 0x44,
                name: "PREVRANDAO".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x45 => Ok(OPCODE {
                opcode: 0x45,
                name: "GASLIMIT".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x46 => Ok(OPCODE {
                opcode: 0x46,
                name: "CHAINID".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x47 => Ok(OPCODE {
                opcode: 0x47,
                name: "SELFBALANCE".to_string(),
                gas: 5,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x48 => Ok(OPCODE {
                opcode: 0x48,
                name: "BASEFEE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),

            0x50 => Ok(OPCODE {
                opcode: 0x50,
                name: "POP".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x51 => Ok(OPCODE {
                opcode: 0x51,
                name: "MLOAD".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x52 => Ok(OPCODE {
                opcode: 0x52,
                name: "MSTORE".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0x53 => Ok(OPCODE {
                opcode: 0x53,
                name: "MSTORE8".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0x54 => Ok(OPCODE {
                opcode: 0x54,
                name: "SLOAD".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 1,
            }),
            0x55 => Ok(OPCODE {
                opcode: 0x55,
                name: "SSTORE".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0x56 => Ok(OPCODE {
                opcode: 0x56,
                name: "JUMP".to_string(),
                gas: 8,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 0,
            }),
            0x57 => Ok(OPCODE {
                opcode: 0x57,
                name: "JUMPI".to_string(),
                gas: 10,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0x58 => Ok(OPCODE {
                opcode: 0x58,
                name: "PC".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 0,
            }),
            0x59 => Ok(OPCODE {
                opcode: 0x59,
                name: "MSIZE".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x5a => Ok(OPCODE {
                opcode: 0x5a,
                name: "GAS".to_string(),
                gas: 2,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x5b => Ok(OPCODE {
                opcode: 0x5b,
                name: "JUMPDEST".to_string(),
                gas: 1,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 0,
            }),

            0x60 => Ok(OPCODE {
                opcode: 0x60,
                name: "PUSH1".to_string(),
                gas: 3,
                oprand_bytes: 1,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x61 => Ok(OPCODE {
                opcode: 0x61,
                name: "PUSH2".to_string(),
                gas: 3,
                oprand_bytes: 2,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x62 => Ok(OPCODE {
                opcode: 0x62,
                name: "PUSH3".to_string(),
                gas: 3,
                oprand_bytes: 3,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x63 => Ok(OPCODE {
                opcode: 0x63,
                name: "PUSH4".to_string(),
                gas: 3,
                oprand_bytes: 4,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x64 => Ok(OPCODE {
                opcode: 0x64,
                name: "PUSH5".to_string(),
                gas: 3,
                oprand_bytes: 5,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x65 => Ok(OPCODE {
                opcode: 0x65,
                name: "PUSH6".to_string(),
                gas: 3,
                oprand_bytes: 6,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x66 => Ok(OPCODE {
                opcode: 0x66,
                name: "PUSH7".to_string(),
                gas: 3,
                oprand_bytes: 7,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x67 => Ok(OPCODE {
                opcode: 0x67,
                name: "PUSH8".to_string(),
                gas: 3,
                oprand_bytes: 8,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x68 => Ok(OPCODE {
                opcode: 0x68,
                name: "PUSH9".to_string(),
                gas: 3,
                oprand_bytes: 9,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x69 => Ok(OPCODE {
                opcode: 0x69,
                name: "PUSH10".to_string(),
                gas: 3,
                oprand_bytes: 10,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6a => Ok(OPCODE {
                opcode: 0x6a,
                name: "PUSH11".to_string(),
                gas: 3,
                oprand_bytes: 11,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6b => Ok(OPCODE {
                opcode: 0x6b,
                name: "PUSH12".to_string(),
                gas: 3,
                oprand_bytes: 12,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6c => Ok(OPCODE {
                opcode: 0x6c,
                name: "PUSH13".to_string(),
                gas: 3,
                oprand_bytes: 13,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6d => Ok(OPCODE {
                opcode: 0x6d,
                name: "PUSH14".to_string(),
                gas: 3,
                oprand_bytes: 14,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6e => Ok(OPCODE {
                opcode: 0x6e,
                name: "PUSH15".to_string(),
                gas: 3,
                oprand_bytes: 15,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x6f => Ok(OPCODE {
                opcode: 0x6f,
                name: "PUSH16".to_string(),
                gas: 3,
                oprand_bytes: 16,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x70 => Ok(OPCODE {
                opcode: 0x70,
                name: "PUSH17".to_string(),
                gas: 3,
                oprand_bytes: 17,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x71 => Ok(OPCODE {
                opcode: 0x71,
                name: "PUSH18".to_string(),
                gas: 3,
                oprand_bytes: 18,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x72 => Ok(OPCODE {
                opcode: 0x72,
                name: "PUSH19".to_string(),
                gas: 3,
                oprand_bytes: 19,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x73 => Ok(OPCODE {
                opcode: 0x73,
                name: "PUSH20".to_string(),
                gas: 3,
                oprand_bytes: 20,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x74 => Ok(OPCODE {
                opcode: 0x74,
                name: "PUSH21".to_string(),
                gas: 3,
                oprand_bytes: 21,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x75 => Ok(OPCODE {
                opcode: 0x75,
                name: "PUSH22".to_string(),
                gas: 3,
                oprand_bytes: 22,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x76 => Ok(OPCODE {
                opcode: 0x76,
                name: "PUSH23".to_string(),
                gas: 3,
                oprand_bytes: 23,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x77 => Ok(OPCODE {
                opcode: 0x77,
                name: "PUSH24".to_string(),
                gas: 3,
                oprand_bytes: 24,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x78 => Ok(OPCODE {
                opcode: 0x78,
                name: "PUSH25".to_string(),
                gas: 3,
                oprand_bytes: 25,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x79 => Ok(OPCODE {
                opcode: 0x79,
                name: "PUSH26".to_string(),
                gas: 3,
                oprand_bytes: 26,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7a => Ok(OPCODE {
                opcode: 0x7a,
                name: "PUSH27".to_string(),
                gas: 3,
                oprand_bytes: 27,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7b => Ok(OPCODE {
                opcode: 0x7b,
                name: "PUSH28".to_string(),
                gas: 3,
                oprand_bytes: 28,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7c => Ok(OPCODE {
                opcode: 0x7c,
                name: "PUSH29".to_string(),
                gas: 3,
                oprand_bytes: 29,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7d => Ok(OPCODE {
                opcode: 0x7d,
                name: "PUSH30".to_string(),
                gas: 3,
                oprand_bytes: 30,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7e => Ok(OPCODE {
                opcode: 0x7e,
                name: "PUSH31".to_string(),
                gas: 3,
                oprand_bytes: 31,
                stack_reads: 0,
                stack_writes: 1,
            }),
            0x7f => Ok(OPCODE {
                opcode: 0x7f,
                name: "PUSH32".to_string(),
                gas: 3,
                oprand_bytes: 32,
                stack_reads: 0,
                stack_writes: 1,
            }),

            0x80 => Ok(OPCODE {
                opcode: 0x80,
                name: "DUP1".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 2,
            }),
            0x81 => Ok(OPCODE {
                opcode: 0x81,
                name: "DUP2".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 3,
            }),
            0x82 => Ok(OPCODE {
                opcode: 0x82,
                name: "DUP3".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 4,
            }),
            0x83 => Ok(OPCODE {
                opcode: 0x83,
                name: "DUP4".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 4,
                stack_writes: 5,
            }),
            0x84 => Ok(OPCODE {
                opcode: 0x84,
                name: "DUP5".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 5,
                stack_writes: 6,
            }),
            0x85 => Ok(OPCODE {
                opcode: 0x85,
                name: "DUP6".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 6,
                stack_writes: 7,
            }),
            0x86 => Ok(OPCODE {
                opcode: 0x86,
                name: "DUP7".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 7,
                stack_writes: 8,
            }),
            0x87 => Ok(OPCODE {
                opcode: 0x87,
                name: "DUP8".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 8,
                stack_writes: 9,
            }),
            0x88 => Ok(OPCODE {
                opcode: 0x88,
                name: "DUP9".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 9,
                stack_writes: 10,
            }),
            0x89 => Ok(OPCODE {
                opcode: 0x89,
                name: "DUP10".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 10,
                stack_writes: 11,
            }),
            0x8a => Ok(OPCODE {
                opcode: 0x8a,
                name: "DUP11".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 11,
                stack_writes: 12,
            }),
            0x8b => Ok(OPCODE {
                opcode: 0x8b,
                name: "DUP12".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 12,
                stack_writes: 13,
            }),
            0x8c => Ok(OPCODE {
                opcode: 0x8c,
                name: "DUP13".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 13,
                stack_writes: 14,
            }),
            0x8d => Ok(OPCODE {
                opcode: 0x8d,
                name: "DUP14".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 14,
                stack_writes: 15,
            }),
            0x8e => Ok(OPCODE {
                opcode: 0x8e,
                name: "DUP15".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 15,
                stack_writes: 16,
            }),
            0x8f => Ok(OPCODE {
                opcode: 0x8f,
                name: "DUP16".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 16,
                stack_writes: 17,
            }),

            0x90 => Ok(OPCODE {
                opcode: 0x90,
                name: "SWAP1".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 2,
            }),
            0x91 => Ok(OPCODE {
                opcode: 0x91,
                name: "SWAP2".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 3,
            }),
            0x92 => Ok(OPCODE {
                opcode: 0x92,
                name: "SWAP3".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 4,
                stack_writes: 4,
            }),
            0x93 => Ok(OPCODE {
                opcode: 0x93,
                name: "SWAP4".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 5,
                stack_writes: 5,
            }),
            0x94 => Ok(OPCODE {
                opcode: 0x94,
                name: "SWAP5".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 6,
                stack_writes: 6,
            }),
            0x95 => Ok(OPCODE {
                opcode: 0x95,
                name: "SWAP6".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 7,
                stack_writes: 7,
            }),
            0x96 => Ok(OPCODE {
                opcode: 0x96,
                name: "SWAP7".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 8,
                stack_writes: 8,
            }),
            0x97 => Ok(OPCODE {
                opcode: 0x97,
                name: "SWAP8".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 9,
                stack_writes: 9,
            }),
            0x98 => Ok(OPCODE {
                opcode: 0x98,
                name: "SWAP9".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 10,
                stack_writes: 10,
            }),
            0x99 => Ok(OPCODE {
                opcode: 0x99,
                name: "SWAP10".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 11,
                stack_writes: 11,
            }),
            0x9a => Ok(OPCODE {
                opcode: 0x9a,
                name: "SWAP11".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 12,
                stack_writes: 12,
            }),
            0x9b => Ok(OPCODE {
                opcode: 0x9b,
                name: "SWAP12".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 13,
                stack_writes: 13,
            }),
            0x9c => Ok(OPCODE {
                opcode: 0x9c,
                name: "SWAP13".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 14,
                stack_writes: 14,
            }),
            0x9d => Ok(OPCODE {
                opcode: 0x9d,
                name: "SWAP14".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 15,
                stack_writes: 15,
            }),
            0x9e => Ok(OPCODE {
                opcode: 0x9e,
                name: "SWAP15".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 16,
                stack_writes: 16,
            }),
            0x9f => Ok(OPCODE {
                opcode: 0x9f,
                name: "SWAP16".to_string(),
                gas: 3,
                oprand_bytes: 0,
                stack_reads: 17,
                stack_writes: 17,
            }),

            0xa0 => Ok(OPCODE {
                opcode: 0xa0,
                name: "LOG0".to_string(),
                gas: 375,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0xa1 => Ok(OPCODE {
                opcode: 0xa1,
                name: "LOG1".to_string(),
                gas: 750,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 0,
            }),
            0xa2 => Ok(OPCODE {
                opcode: 0xa2,
                name: "LOG2".to_string(),
                gas: 1125,
                oprand_bytes: 0,
                stack_reads: 4,
                stack_writes: 0,
            }),
            0xa3 => Ok(OPCODE {
                opcode: 0xa3,
                name: "LOG3".to_string(),
                gas: 1500,
                oprand_bytes: 0,
                stack_reads: 5,
                stack_writes: 0,
            }),
            0xa4 => Ok(OPCODE {
                opcode: 0xa4,
                name: "LOG4".to_string(),
                gas: 1875,
                oprand_bytes: 0,
                stack_reads: 6,
                stack_writes: 0,
            }),

            0xf0 => Ok(OPCODE {
                opcode: 0xf0,
                name: "CREATE".to_string(),
                gas: 32000,
                oprand_bytes: 0,
                stack_reads: 3,
                stack_writes: 1,
            }),
            0xf1 => Ok(OPCODE {
                opcode: 0xf1,
                name: "CALL".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 7,
                stack_writes: 1,
            }),
            0xf2 => Ok(OPCODE {
                opcode: 0xf2,
                name: "CALLCODE".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 7,
                stack_writes: 1,
            }),
            0xf3 => Ok(OPCODE {
                opcode: 0xf3,
                name: "RETURN".to_string(),
                gas: 0,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0xf4 => Ok(OPCODE {
                opcode: 0xf4,
                name: "DELEGATECALL".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 6,
                stack_writes: 1,
            }),
            0xf5 => Ok(OPCODE {
                opcode: 0xf5,
                name: "CREATE2".to_string(),
                gas: 32000,
                oprand_bytes: 0,
                stack_reads: 4,
                stack_writes: 1,
            }),
            0xfa => Ok(OPCODE {
                opcode: 0xfa,
                name: "STATICCALL".to_string(),
                gas: 100,
                oprand_bytes: 0,
                stack_reads: 6,
                stack_writes: 1,
            }),
            0xfd => Ok(OPCODE {
                opcode: 0xfd,
                name: "REVERT".to_string(),
                gas: 0,
                oprand_bytes: 0,
                stack_reads: 2,
                stack_writes: 0,
            }),
            0xfe => Ok(OPCODE {
                opcode: 0xfe,
                name: "INVALID".to_string(),
                gas: 0,
                oprand_bytes: 0,
                stack_reads: 0,
                stack_writes: 0,
            }),
            0xff => Ok(OPCODE {
                opcode: 0xff,
                name: "SELFDESTRUCT".to_string(),
                gas: 5000,
                oprand_bytes: 0,
                stack_reads: 1,
                stack_writes: 0,
            }),
            _ => Err("TryFrom<u8> UNKNOWN OPCODE"),
        }
    }
}

impl TryFrom<&str> for OPCODE {
    type Error = &'static str;
    fn try_from(value: &str) -> Result<Self, Self::Error> {
        let mut index = 0;
        while index < 255 {
            let op = match OPCODE::try_from(index) {
                Ok(op) => op,
                Err(_) => {
                    index = index + 1;
                    continue;
                }
            };
            if op.name == value.to_string() {
                return Ok(op);
            }
            index = index + 1;
        }
        Err("TryFrom<&str> UNKONW OP NAME")
    }
}

use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    pub static ref OPCODE_MAP: HashMap<u8, &'static str> = {
        let map = HashMap::from([
            (0x00, "STOP"),
            (0x01, "ADD"),
            (0x02, "MUL"),
            (0x03, "SUB"),
            (0x04, "DIV"),
            (0x05, "SDIV"),
            (0x06, "MOD"),
            (0x07, "SMOD"),
            (0x08, "ADDMOD"),
            (0x09, "MULMOD"),
            (0x0a, "EXP"),
            (0x0b, "SIGNEXTEND"),
            (0x10, "LT"),
            (0x11, "GT"),
            (0x12, "SLT"),
            (0x13, "SGT"),
            (0x14, "EQ"),
            (0x15, "ISZERO"),
            (0x16, "AND"),
            (0x17, "OR"),
            (0x18, "XOR"),
            (0x19, "NOT"),
            (0x1a, "BYTE"),
            (0x1b, "SHL"),
            (0x1c, "SHR"),
            (0x1d, "SAR"),
            (0x20, "SHA3"),
            (0x30, "ADDRESS"),
            (0x31, "BALANCE"),
            (0x32, "ORIGIN"),
            (0x33, "CALLER"),
            (0x34, "CALLVALUE"),
            (0x35, "CALLDATALOAD"),
            (0x36, "CALLDATASIZE"),
            (0x37, "CALLDATACOPY"),
            (0x38, "CODESIZE"),
            (0x39, "CODECOPY"),
            (0x3a, "GASPRICE"),
            (0x3b, "EXTCODESIZE"),
            (0x3c, "EXTCODECOPY"),
            (0x3d, "RETURNDATASIZE"),
            (0x3e, "RETURNDATACOPY"),
            (0x3f, "EXTCODEHASH"),
            (0x40, "BLOCKHASH"),
            (0x41, "COINBASE"),
            (0x42, "TIMESTAMP"),
            (0x43, "NUMBER"),
            (0x44, "PREVRANDAO"),
            (0x45, "GASLIMIT"),
            (0x46, "CHAINID"),
            (0x47, "SELFBALANCE"),
            (0x48, "BASEFEE"),
            (0x50, "POP"),
            (0x51, "MLOAD"),
            (0x52, "MSTORE"),
            (0x53, "MSTORE8"),
            (0x54, "SLOAD"),
            (0x55, "SSTORE"),
            (0x56, "JUMP"),
            (0x57, "JUMPI"),
            (0x58, "PC"),
            (0x59, "MSIZE"),
            (0x5a, "GAS"),
            (0x5b, "JUMPDEST"),
            (0x60, "PUSH1"),
            (0x61, "PUSH2"),
            (0x62, "PUSH3"),
            (0x63, "PUSH4"),
            (0x64, "PUSH5"),
            (0x65, "PUSH6"),
            (0x66, "PUSH7"),
            (0x67, "PUSH8"),
            (0x68, "PUSH9"),
            (0x69, "PUSH10"),
            (0x6a, "PUSH11"),
            (0x6b, "PUSH12"),
            (0x6c, "PUSH13"),
            (0x6d, "PUSH14"),
            (0x6e, "PUSH15"),
            (0x6f, "PUSH16"),
            (0x70, "PUSH17"),
            (0x71, "PUSH18"),
            (0x72, "PUSH19"),
            (0x73, "PUSH20"),
            (0x74, "PUSH21"),
            (0x75, "PUSH22"),
            (0x76, "PUSH23"),
            (0x77, "PUSH24"),
            (0x78, "PUSH25"),
            (0x79, "PUSH26"),
            (0x7a, "PUSH27"),
            (0x7b, "PUSH28"),
            (0x7c, "PUSH29"),
            (0x7d, "PUSH30"),
            (0x7e, "PUSH31"),
            (0x7f, "PUSH32"),
            (0x80, "DUP1"),
            (0x81, "DUP2"),
            (0x82, "DUP3"),
            (0x83, "DUP4"),
            (0x84, "DUP5"),
            (0x85, "DUP6"),
            (0x86, "DUP7"),
            (0x87, "DUP8"),
            (0x88, "DUP9"),
            (0x89, "DUP10"),
            (0x8a, "DUP11"),
            (0x8b, "DUP12"),
            (0x8c, "DUP13"),
            (0x8d, "DUP14"),
            (0x8e, "DUP15"),
            (0x8f, "DUP16"),
            (0x90, "SWAP1"),
            (0x91, "SWAP2"),
            (0x92, "SWAP3"),
            (0x93, "SWAP4"),
            (0x94, "SWAP5"),
            (0x95, "SWAP6"),
            (0x96, "SWAP7"),
            (0x97, "SWAP8"),
            (0x98, "SWAP9"),
            (0x99, "SWAP10"),
            (0x9a, "SWAP11"),
            (0x9b, "SWAP12"),
            (0x9c, "SWAP13"),
            (0x9d, "SWAP14"),
            (0x9e, "SWAP15"),
            (0x9f, "SWAP16"),
            (0xa0, "LOG0"),
            (0xa1, "LOG1"),
            (0xa2, "LOG2"),
            (0xa3, "LOG3"),
            (0xa4, "LOG4"),
            (0xf0, "CREATE"),
            (0xf1, "CALL"),
            (0xf2, "CALLCODE"),
            (0xf3, "RETURN"),
            (0xf4, "DELEGATECALL"),
            (0xf5, "CREATE2"),
            (0xfa, "STATICCALL"),
            (0xfd, "REVERT"),
            (0xfe, "INVALID"),
            (0xff, "SELFDESTRUCT"),
        ]);
        map
    };
}
